/*
 * This source file was generated by the Gradle 'init' task
 */
package ucsc.th.quarter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

public class App {
    String dataDir = "testdata";

    public void createFolder() {
        Path folderPath = Path.of(dataDir);
        try {
            Files.createDirectories(folderPath);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public Path createFile(String fileName, int lines) {
        Path path = Path.of(dataDir+'/'+fileName);
        try {
            Files.writeString(path, (fileName+"\n").repeat(lines),
                        StandardOpenOption.CREATE,
                        StandardOpenOption.APPEND);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return path;
    }

    public void displayFile(Path file) {
        try {
            System.out.print(Files.readString(file));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public String getGreeting() {
        createFolder();
        Path f1 = createFile("f1.txt", 3);
        Path f2 = createFile("f2.txt", 27);
        Path f3 = createFile("f3.txt", 7);
        displayFile(f1);
        displayFile(f2);
        displayFile(f3);
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
